platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk'

inputs:
  - name: amazing-app-git

outputs:
  - name: deploy

run:
  path: amazing-app-git/ci/scripts/build.sh
  args:
    - amazing-app-git